### ISSUE TITLE
Increasing border-radius of the main input

### ISSUE THREAD

**Issue by alikhalilifar** [tekinnigar1/golden#3]
After increasing the height of the input, border radius should be increased too.

Current:
![image](https://github.com/tekinnigar1/golden/assets/6498743/97ce1519-d8c5-4510-aff5-4cc7044a0fd8)

Figma design:
![image](https://github.com/tekinnigar1/golden/assets/6498743/bd886acd-589a-4f95-8853-7477f4ed45c5)

**Comment by tekinnigar1** [comment]
fixed

**Comment by tekinnigar1** [comment]
done
